# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,   r: 'release'}
          - {os: windows-latest,   r: 'oldrel-1'}
          - {os: windows-latest,   r: 'oldrel-2'}
          - {os: windows-latest,   r: 'oldrel-3'}
          - {os: windows-latest,   r: 'oldrel-4'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::sessioninfo
            rstudio/shinycoreci
            rappdirs
          needs: check
          cache: false

      - name: Repo status
        shell: Rscript {0}
        run: | 
          for (packages in list(
            c("rsconnect", "shiny", "schloerke/shinyjster", "shinytest2", "shinycoreci"),
            c("shiny", "shinytest2", "shinycoreci")
          )) {
            message("\n\n\n\n\n\n\n\nStarting callr to install: ")
            print(packages)
          
            callr::r(
              function(packages, upgrade, dependencies) {          
                # Performing a leap of faith that pak is installed.
                # Avoids weird installs when using pak to install shinycoreci
                stopifnot(utils::packageVersion("pak") >= "0.3.0")
                pak__pkg_install <- utils::getFromNamespace("pkg_install", "pak")
                pak__pkg_install(
                  packages,
                  ask = FALSE, # Not interactive, so don't ask
                  upgrade = upgrade,
                  dependencies = dependencies
                )
              },
              list(
                packages = packages,
                upgrade = TRUE,
                dependencies = NA
              ),
              show = TRUE,
              supervise = TRUE,
              spinner = TRUE # helps with CI from timing out
            )
          }
